INSERT INTO countries (country) VALUES
('Antigua and Barbuda'),
('Argentina'),
('Austria'),
('Bahamas'),
('Barbados'),
('Belgium'),
('Belize'),
('Bolivia'),
('Brazil'),
('Bulgaria'),
('Canada'),
('Chile'),
('Colombia'),
('Costa Rica'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('El Salvador'),
('Estonia'),
('Finland'),
('France'),
('Germany'),
('Greece'),
('Grenada'),
('Guatemala'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hungary'),
('Ireland'),
('Italy'),
('Jamaica'),
('Latvia'),
('Lithuania'),
('Luxembourg'),
('Malta'),
('Mexico'),
('Netherlands'),
('Nicaragua'),
('Panama'),
('Paraguay'),
('Peru'),
('Poland'),
('Portugal'),
('Romania'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Vincent and the Grenadines'),
('Slovakia'),
('Slovenia'),
('Spain'),
('Suriname'),
('Sweden'),
('Trinidad and Tobago'),
('United States'),
('Uruguay'),
('Venezuela');
